openapi: 3.0.0
info:
  title: Mitlaeufer API
  description: Backend API for "Mitlaeufer - hiking together"
  license:
    name: MIT
  version: 0.9.0
servers:
  - url: http://localhost:8080
    description: Development API
paths:
  /:
    get:
      summary: Health check
      responses:
        200:
          description: OK
